### PR TITLE
[WIP] Collection view animations

### PR DESCRIPTION
**Pull request by aranasaurus**
This PR adresses #48.

I wasn't sure of the best way to do this with the state of the dev branch, but it's a one line change, I'll be happy to move it elsewhere, if this isn't the right way to go about it.

I also wanted to add a test for it, but seemed like maybe more work than it was worth especially with the impending refactor ;)

### CODE REVIEW

**Comment by danthorpe** [comment]
Arr.... err I'm about to call it a night. For the moment, can you hold off on this change on your fork?

Tomorrow I'll see about getting `master` or `development` in a better shape while I'm refactoring stuff.

Thanks for the fixes! - sorry everything has got a bit screwed up here. Ideally this would go into `development` with an issue.

**Comment by aranasaurus** [comment]
haha, yeah, no worries, I'd figured you'd already be offline for the night! Like I said I'm happy to send this where ever you like, I just wanted to get the ball rolling on it (and actually contribute _something_ back to one of your projects!).

**Comment by danthorpe** [comment]
@aranasaurus - is there any chance you can pull my `development` branch into your branch here and push again?

**Comment by danthorpe** [comment]
@aranasaurus - sorry it's taken me so long to get round to this PR... 😔

**Comment by aranasaurus** [comment]
@danthorpe It should probably just be closed, the salient bit is a one line change, the first commit was just to get tests passing before I started, which is a commit that will probably just disappear when switching to `development` with the changes there.

I also found that there's a bit more needed to address what's in #48, so, yeah, closing this and I'll try again as soon as I can.

**Pull request closed without merging**
