### PR TITLE
TaylorSource needs a bit of attention...

### PR DESCRIPTION
**Pull request by danthorpe**
Taylor needs a bit of attention:
- [ ] Update project structure, use `@testable`
- [ ] Refactor key components to use Swift 2.0 error handling.
- [ ] Refactor to use Swift 2.2 syntax.
- [ ] Figure out priority list of what needs to have tests written

### CODE REVIEW

**Comment by aranasaurus** [comment]
@danthorpe You'd asked me for some feedback on this issue so here goes!
- I think the most difficult bit has been documentation related and the fact that a lot of the things used by TaylorSource are in Yap Database Extensions, but feels like they're only really meant to be used by TaylorSource since they aren't documented (or even mentioned in the readme) over there aside from header docs, nor are they really documented here, so it kinda feels like a bunch of code in YapDB Extensions that's just there to support TaylorSource. This is compounded by the sense that Yap Database Extensions, from the readme, seems like it is solely about persisting model objects from value types. Basically everything in Core/YapDB.swift in YapDatabaseExtensions, feels like it should either be in TaylorSource or the transactions there need to be able to read from views maybe? Anyway, tangent! ;) Once I got it figured out how all the pieces fit together they're great to use, it was just fairly difficult to piece it all together.
- One thing that I'd like to be able to do but couldn't with the current API (of both YapDB Extensions and by proxy TaylorSource) was I'd like to be able to tweak the `blockInvokeOptions` on my View grouping/sorting so that I could optimize the frequency of those blocks being called beyond just the type of block given. In my situation when the sorting/grouping _does_ need to be called it needs the data from the object and metadata but only really needs to be run when I manually "touch" it and on insert.

Aside from the crash/exception thing mentioned elsewhere that's really the biggest stuff I can think of. I'll add more if I think of any!

**Comment by danthorpe** [comment]
Thanks @aranasaurus - that's is a really good point about `YapDB.*` types and documentation/discoverability and I totally agree with you.

To give some historical perspective, the concepts for all of this code was first written all together in an application. I later re-wrote it and open sourced it. TaylorSource was the first thing I did, but just the "basic" datasource stuff. I then added the YapDatabase components _after_ I did YapDatabaseExtensions.

In hindsight, it makes a lot more sense to move all those views and bits and bobs into TaylorSource.

Interesting idea about the `blockInvokeOptions` - haven't really ever looked at these, will check it out.

**Comment by aranasaurus** [comment]
@danthorpe I was trying to work around the NSInternalConsistency crash yesterday by disabling updates when the view is off-screen (it's crashing when we log in/out which takes place on another screen), and it wasn't really clear on how I could use `shouldPerformUpdates` with a collection view. I ended up making my provider have a flag which I can set from the VC on `viewWillDisappear/Appear` and then the `processChanges` block that I pass in to the `YapDBDatasource` guards against that flag. It seemed like the TableView version had this kind of functionality built-in with the `tay_` methods, but the CollectionView versions of those methods don't seem to be called.

I thought I'd bring that up here as this is another "pain point" with the current version.

**Comment by danthorpe** [comment]
Thanks @aranasaurus for highlighting this. It's on the list - progress has not been the fastest on this so far. But have been sorting out some of the infrastructure.

Also... kinda thinking of moving straight to Swift 2.2 / Xcode 7.3 for this re-working stuff. Now sure how that sounds to you...

**Comment by aranasaurus** [comment]
We have not moved on to Swift 2.2 / Xcode 7.3 yet... but we probably should............

**Comment by aranasaurus** [comment]
Another very minor thing that just occurred to me as "kinda weird"... UIKit says "DataSource", TaylorSource says "Datasource" ¯_(ツ)_/¯

**Comment by aranasaurus** [comment]
I discovered today that the `YapDB.YapDatabaseExtensionRegistrar` stuff doesn't have `async` registration methods. That'd be a nice to have, I think, unless there's some reason that was avoided.

**Comment by danthorpe** [comment]
Yeah, the async registration is a good point. Basically, it isn't used by any of the stuff in YapDB because typically it all just works by registering the views as needed by the `Factory`, and this is all fairly synchronous, as otherwise you wouldn't be able to set the `tableViewDataSource` on the `tableView` until that had returned.... 

But.. registering this synchronously can sometimes give you a performance penalty if you have a big database, and you register new views all the time (because maybe they're dynamic?).

If I could figure out a way to make it work with asynchronous registration, without making it more complex then I absolutely would. I think if you have relatively "static" views then it is not a significant issue. You can register views upfront when you create the database. (see `YapDB.databaseNamed()` function which takes a configuration block).

For really dynamic views which change all the time - then I recommend re-thinking the approach, as I'm not sure how beneficial such views even are.

**Comment by aranasaurus** [comment]
> For really dynamic views which change all the time - then I recommend re-thinking the approach, as I'm not sure how beneficial such views even are.

Our use case was for the Search Results view. We have several Sort views and we only pre-register the search results view for the currently selected sort view. The search bar is on a menu, and not needed immediately, so we register that asynchronously when we create the datasource provider for the "all results" side of the search (which _is_ needed immediately). We _could_ pre-register a search view for every sort option, but that seemed like a lot of extra unnecessary processing for the common case (which is the search view never getting seen by the user). 

Not a big deal, since we can just do the registration asynchronously ourselves, but thought I'd bring it up just in case :)

**Pull request closed without merging**
